### ISSUE TITLE
File root is public to access.

### ISSUE THREAD

**Issue by SjamonDaal** [Addono/LISA#24]
In the current setup there is an issue that all files are accessible from the web.
You can just access the html file "/application/index.html", but also the git records and everything.

This is not best practise.

An easy fix will be to create a "public" folder in the root dir.
create a softlink to the ./index.php file. (`cd public && ln -s ../index.php index.php`)

Then set your apache web root to `/var/www/vhosts/LISA/public` and fix all issues.

**Comment by Addono** [comment]
Hey! Thanks for taking the time to create an issue.

Yes, you are right that the current deployment strategy is sub-optimal. It's kinda due to how CodeIgniter constructs their repository by default. 

For now the only security issue I see is that the Git folder is exposed, even though the repository is public might it be that downstream deployments include secrets or that sensitive information is stored locally in the repository, e.g. in `/.git/config`.

Anyway, personally not too fond of using symlinks, as it's an imperative way to address to problem, except maybe if it would be in some automation script, like a CICD pipeline. 

Instead my preference goes to some declarative method like nginx config. I quickly mashed a PR together (#25), my nginx experience is quite limited, so if you would have time to give it a look and provide feedback, then that would be appreciated.

**Comment by Addono** [comment]
Obviously, the downside of this approach is deployments use their own configuration files for the webserver, then this fix - and any future similar ones - will be ignored.

**Comment by SjamonDaal** [comment]
If this is how CodeIgniter works in the default setup, is CodeIgniter still the best solution for this project? I see a lot of potential on this project and I've a lot of ideas to add to this system like auto topup via a tikkie QR code or some other payment gateway, multiple products with different values, settings to disable payments on someone else's account etc.

If you think this app is what it is and does what it needs to do thats fine too.

**Comment by Addono** [comment]
No, CodeIgniter is definitely not the future nor the best choice for the project. 

Imo, the project has reached legacy stage a couple years ago. It works as it is supposed to be working, doesn't have any known bugs and also no major feature requests. Once in a while I make some small additions to it, just for fun, but the dev experience is bad for me, not to talk about on boarding new developers.

Switching away from CodeIgniter is not going to be easy at all, and that's because of me 😅. I wrote an abstraction layer/"framework like thing" on top of CI onto which LISA is written. Hence, the business logic of LISA has quite some assumptions which will not be met by any other framework where one would like to migrate it to.

In the end, it's probably less time consuming to rewrite the entire application in a more modern software stack (e.g. Facebook's React+GraphQL) when the need for some new major feature arrises.

Security fixes however are still important, as there is still at least one copy in production. So thank you for pointing out the public files issue out!

**Comment by Addono** [comment]
@all-contributors please add SjamonDaal for security, infra
